config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :settlebuddy_supports

  resources :requests

  resources :links

  resources :document_comments

  resources :conversations

  resources :messages

  resources :documents

  resources :comments

  resources :subtasks

  resources :tasks

  resources :roadmaps

  get 'static_pages/home'

  root 'static_pages#home'
  get 'search/settlebuddies'

  get 'search/request_settle'
  get 'search/requests_to_settle'
  get 'search/settle_request'
  get 'search/library'
  get 'search/search_settle_buddy'
  get 'search/search_library'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks", sessions: "users/sessions", registrations: 'users/registrations'}
  devise_scope :user do
    get "/logout" => "users/sessions#destroy"
  end
  as :user do
    get 'users', :to => 'users/registrations#edit', :as => :user_root # Rails 3
  end
  match '/contact_forms',     to: 'contact_forms#new',             via: 'get'
  resources "contact_forms", only: [:new, :create]

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :task
end

app/models/contact_form.rb
class ContactForm < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :file,      :attachment => true

  attribute :message
  attribute :telephone

  attribute :nickname,  :captcha  => true
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Getgo Contact Form",
      :to => "info@getgoabroad.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
	has_many :messages
	belongs_to :user
end

app/models/document.rb
class Document < ActiveRecord::Base
	belongs_to :task
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :task
end

app/models/message.rb
class Message < ActiveRecord::Base
	belongs_to :conversation
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/request.rb
class Request < ActiveRecord::Base
end

app/models/roadmap.rb
class Roadmap < ActiveRecord::Base
	has_many :tasks
	belongs_to :user
  ratyrate_rateable "roadmap"
end

app/models/subtask.rb
class Subtask < ActiveRecord::Base
	belongs_to :task
end

app/models/task.rb
class Task < ActiveRecord::Base
  has_many :subtasks
  belongs_to :roadmap
  has_many :documents
  has_many :comments
  has_many :document_comments
  has_many :links

end

app/models/user.rb
class User < ActiveRecord::Base
  include Gravtastic
  gravtastic
  ratyrate_rater
  ratyrate_rateable "user"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
              :omniauthable,  :omniauth_providers => [:facebook]
  validates :name, presence: true
  validates :country_of_origin, presence: true
  validates :city_of_studies, presence: true
  validates :duration, presence: true
  validates :birthdate, presence: true
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.password = Devise.friendly_token[0,20]
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
        user.name = data["name"] if user.name.blank?
        user.provider = "facebook" if user.provider.blank?
        user.uid = data["id"] if user.uid.blank?

      end
    end
  end

  def self.find_for_facebook_oauth(access_token, signed_in_resource=nil)
    data = access_token.extra.raw_info
    if user = User.where(:email => data.email).first
    user
    else # Create a user with a stub password.
      user =User.new
    user
    end
  end
  has_one :roadmap
  has_one :settlebuddy_support
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  before_action :set_subtask, only: [:show, :edit, :update, :destroy]

  # GET /subtasks
  # GET /subtasks.json
  def index
    @subtasks = Subtask.all
  end

  # GET /subtasks/1
  # GET /subtasks/1.json
  def show
  end

  # GET /subtasks/new
  def new
    @subtask = Subtask.new
  end

  # GET /subtasks/1/edit
  def edit
  end

  # POST /subtasks
  # POST /subtasks.json
  def create
    @subtask = Subtask.new(subtask_params)

    respond_to do |format|
      if @subtask.save
        format.html { redirect_to @subtask, notice: 'Subtask was successfully created.' }
        format.json { render :show, status: :created, location: @subtask }
      else
        format.html { render :new }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subtasks/1
  # PATCH/PUT /subtasks/1.json
  def update
    respond_to do |format|
      if @subtask.update(subtask_params)
        format.html { redirect_to @subtask, notice: 'Subtask was successfully updated.' }
        format.json { render :show, status: :ok, location: @subtask }
      else
        format.html { render :edit }
        format.json { render json: @subtask.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subtasks/1
  # DELETE /subtasks/1.json
  def destroy
    @subtask.destroy
    respond_to do |format|
      format.html { redirect_to subtasks_url, notice: 'Subtask was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subtask
      @subtask = Subtask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subtask_params
      params.require(:subtask).permit(:description, :done, :deadline, :name, :task_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
    :count => resource.errors.count,
    :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      
      #{messages} </br>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/subtasks_helper.rb
module SubtasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/subtasks/_form.html.erb
<%= form_for(@subtask) do |f| %>
  <% if @subtask.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subtask.errors.count, "error") %> prohibited this subtask from being saved:</h2>

      <ul>
      <% @subtask.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="field">
    <%= f.label :deadline %><br>
    <%= f.date_select :deadline %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subtasks/edit.html.erb
<h1>Editing Subtask</h1>

<%= render 'form' %>

<%= link_to 'Show', @subtask %> |
<%= link_to 'Back', subtasks_path %>

app/views/subtasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subtasks</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Done</th>
      <th>Deadline</th>
      <th>Name</th>
      <th>Task</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subtasks.each do |subtask| %>
      <tr>
        <td><%= subtask.description %></td>
        <td><%= subtask.done %></td>
        <td><%= subtask.deadline %></td>
        <td><%= subtask.name %></td>
        <td><%= subtask.task_id %></td>
        <td><%= link_to 'Show', subtask %></td>
        <td><%= link_to 'Edit', edit_subtask_path(subtask) %></td>
        <td><%= link_to 'Destroy', subtask, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subtask', new_subtask_path %>

app/views/subtasks/new.html.erb
<h1>New Subtask</h1>

<%= render 'form' %>

<%= link_to 'Back', subtasks_path %>

app/views/subtasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @subtask.description %>
</p>

<p>
  <strong>Done:</strong>
  <%= @subtask.done %>
</p>

<p>
  <strong>Deadline:</strong>
  <%= @subtask.deadline %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subtask.name %>
</p>

<p>
  <strong>Task:</strong>
  <%= @subtask.task_id %>
</p>

<%= link_to 'Edit', edit_subtask_path(@subtask) %> |
<%= link_to 'Back', subtasks_path %>